### ISSUE TITLE
username password

### ISSUE THREAD

**Issue by ibrahimcss** [abhaysbharadwaj/SIM808_MQTT_GPS_Tracker#1]
How to add username and password ?

**Comment by abhaysbharadwaj** [comment]
This is a very simple library that does not use username and password for MQTT connection. You can check MQTT doc to add username and password as part of the data packet.

**Comment by ibrahimcss** [comment]
thank you sir, I solved the problem with username and password

Outlook Mobile<https://aka.ms/blhgte>'dan gönderildi

________________________________
